include $(TOPDIR)/rules.mk

LUCI_TITLE:=R619AC Personal OS management
LUCI_DEPENDS:=+luci-base +rpcd-mod-ucode
LUCI_PKGARCH:=all

PKG_MAINTAINER:=R619AC-OS
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk
